spring:
  application:
    name: GerenciadorTarefas
  datasource:
    url: jdbc:h2:mem:tarefas_db
    username: sa
    password: 123
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  web:
    resources:
      static-locations: classpath:/static/